# Generated by Django 4.1.2 on 2023-02-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_attendance_date_alter_attendance_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('出席', '出席'), ('遅刻', '遅刻'), ('欠席', '欠席'), ('早退', '早退')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
    ]
