# Generated by Django 4.1.2 on 2023-02-26 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_attendance_log_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_log',
            name='in_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
