# Generated by Django 4.1.2 on 2023-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_attendance_log_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
