# Generated by Django 4.1.2 on 2023-02-27 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0009_lesson_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('月曜', '月曜'), ('火曜', '火曜'), ('水曜', '水曜'), ('木曜', '木曜'), ('金曜', '金曜'), ('土曜', '土曜'), ('日曜', '日曜')], max_length=5)),
                ('lasson_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time1', models.TimeField(blank=True, null=True)),
                ('end_time1', models.TimeField(blank=True, null=True)),
                ('lasson_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time2', models.TimeField(blank=True, null=True)),
                ('end_time2', models.TimeField(blank=True, null=True)),
                ('lasson_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time3', models.TimeField(blank=True, null=True)),
                ('end_time3', models.TimeField(blank=True, null=True)),
                ('lasson_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time4', models.TimeField(blank=True, null=True)),
                ('end_time4', models.TimeField(blank=True, null=True)),
                ('lasson_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time5', models.TimeField(blank=True, null=True)),
                ('end_time5', models.TimeField(blank=True, null=True)),
                ('lasson_name6', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time6', models.TimeField(blank=True, null=True)),
                ('end_time6', models.TimeField(blank=True, null=True)),
                ('lasson_name7', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time7', models.TimeField(blank=True, null=True)),
                ('end_time7', models.TimeField(blank=True, null=True)),
                ('lasson_name8', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time8', models.TimeField(blank=True, null=True)),
                ('end_time8', models.TimeField(blank=True, null=True)),
                ('lasson_name9', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time9', models.TimeField(blank=True, null=True)),
                ('end_time9', models.TimeField(blank=True, null=True)),
                ('lasson_name10', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time10', models.TimeField(blank=True, null=True)),
                ('end_time10', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
