# Generated by Django 4.1.2 on 2023-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_log',
            name='in_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_log',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
